name: CI/CD

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["Deploy Frontend", "Deploy Backend"]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Deploy frontend
        uses: "ghcr.io/gatsbyjs/actions/deploy@v3"
        with:
          app: "frontend"
          dir: "dist"
          token: ${{ secrets.GITHUB_TOKEN }}

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run Go tests
        run: go test ./...

      - name: Build backend
        run: go build -o main .

      - name: Deploy backend
        uses: "deployments/github-releases@v1"
        with:
          name: "MyApp Backend"
          token: ${{ secrets.GITHUB_TOKEN }}
